### ISSUE TITLE
pip install karta fails if numpy isn't already installed

### ISSUE THREAD

**Issue by benasher44** [njwilson23/karta#23] opened 2015-08-15 02:48 UTC
Because setup.py imports numpy, karta cannot be installed unless numpy is already installed. This feels a bit odd, since numpy is an external dependency of karta and may not be available at install time.
```
benasher$ pip install karta
Collecting karta
  Using cached karta-0.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/3w/68cpb10s359538q_8rj2fpsh0000gn/T/pip-build-lwd1y5r7/karta/setup.py", line 5, in <module>
        import numpy
    ImportError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3w/68cpb10s359538q_8rj2fpsh0000gn/T/pip-build-lwd1y5r7/karta
```

**Comment by njwilson23** [comment] 2015-08-15 07:06
Good point. A potential solution is given at http://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py, but I need some time to wrap my head around how it works. I'm travelling, but will try to fix this when I get some time.

**Comment by benasher44** [comment] 2015-08-16 02:39
Sounds good. Thanks!

**Comment by njwilson23** [comment] 2015-08-18 06:15
There's a branch [numpyless-install](https://github.com/njwilson23/karta/tree/numpyless-install), and I think it should work as of commit c7c45c7f4bd798066e62b9ea2a697e00c09e9664. I want to get this into travis before merging to master, and it would be nice to know if it worked for anyone besides me.

**Comment by benasher44** [comment] 2015-08-18 13:59
Well, now I have a new issue, which doesn't appear to happen if I go with the previous setup and install numpy before I install karta.

Previous (in a fresh virtualenv):
```pip install cython```
```pip install numpy```
```pip install karta```

The above combination works well (although not ideal because installing numpy first is required). With this branch (numpyless-install), I tried the following (in a fresh virtualenv):

```pip install cython```
```pip install --no-cache-dir -e git+https://github.com/njwilson23/karta@numpyless-install#egg=karta-dev``` (fetch from this branch and ensure that pip will not use a cached karta)

This gives me the following output:

```
Obtaining karta from git+https://github.com/njwilson23/karta@numpyless-install#egg=karta-dev
  Cloning https://github.com/njwilson23/karta (to numpyless-install) to /Users/benasher/Code/Python/venvs/karta_test/src/karta
Collecting numpy>=1.6 (from karta)
  Downloading numpy-1.9.2-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 12.1MB/s 
Collecting pyproj>=1.9 (from karta)
  Downloading pyproj-1.9.4.tar.gz (7.8MB)
    100% |████████████████████████████████| 7.8MB 9.7MB/s 
Collecting pyshp>=1.2 (from karta)
  Downloading pyshp-1.2.3.tar.gz
Installing collected packages: numpy, pyproj, pyshp, karta
  Running setup.py install for pyproj
  Running setup.py install for pyshp
  Running setup.py develop for karta
    Complete output from command /Users/benasher/Code/Python/venvs/karta_test/bin/python3.4 -c "import setuptools, tokenize; __file__='/Users/benasher/Code/Python/venvs/karta_test/src/karta/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing requirements to karta.egg-info/requires.txt
    writing dependency_links to karta.egg-info/dependency_links.txt
    writing top-level names to karta.egg-info/top_level.txt
    writing karta.egg-info/PKG-INFO
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'karta.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'doc'
    warning: no files found matching '*.c' under directory 'karta'
    no previously-included directories found matching 'karta/tests'
    writing manifest file 'karta.egg-info/SOURCES.txt'
    running build_ext
    Compiling karta/raster/crfuncs.pyx because it changed.
    Compiling karta/vector/_cvectorgeo.pyx because it changed.
    [1/2] Cythonizing karta/raster/crfuncs.pyx
    [2/2] Cythonizing karta/vector/_cvectorgeo.pyx
    [<setuptools.extension.Extension object at 0x10912a8d0>, <setuptools.extension.Extension object at 0x109129358>]
    building 'karta.raster.crfuncs' extension
    creating build
    creating build/temp.macosx-10.10-x86_64-3.4
    creating build/temp.macosx-10.10-x86_64-3.4/karta
    creating build/temp.macosx-10.10-x86_64-3.4/karta/raster
    clang -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/include/python3.4m -I/Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include -I/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/include/python3.4m -I/Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include -c karta/raster/crfuncs.c -o build/temp.macosx-10.10-x86_64-3.4/karta/raster/crfuncs.o
    In file included from karta/raster/crfuncs.c:259:
    In file included from /Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:
    In file included from /Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:
    /Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    In file included from karta/raster/crfuncs.c:259:
    In file included from /Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:26:
    /Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include/numpy/__multiarray_api.h:1629:1: warning: unused function '_import_array' [-Wunused-function]
    _import_array(void)
    ^
    In file included from karta/raster/crfuncs.c:260:
    In file included from /Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include/numpy/ufuncobject.h:317:
    /Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: unused function '_import_umath' [-Wunused-function]
    _import_umath(void)
    ^
    karta/raster/crfuncs.c:8338:28: warning: unused function '__Pyx_PyObject_AsString' [-Wunused-function]
    static CYTHON_INLINE char* __Pyx_PyObject_AsString(PyObject* o) {
                               ^
    karta/raster/crfuncs.c:8335:32: warning: unused function '__Pyx_PyUnicode_FromString' [-Wunused-function]
    static CYTHON_INLINE PyObject* __Pyx_PyUnicode_FromString(const char* c_str) {
                                   ^
    karta/raster/crfuncs.c:8450:33: warning: unused function '__Pyx_PyIndex_AsSsize_t' [-Wunused-function]
    static CYTHON_INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject* b) {
                                    ^
    karta/raster/crfuncs.c:8512:33: warning: unused function '__Pyx_PyInt_FromSize_t' [-Wunused-function]
    static CYTHON_INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t ival) {
                                    ^
    karta/raster/crfuncs.c:6788:32: warning: unused function '__Pyx_GetItemInt_List_Fast' [-Wunused-function]
    static CYTHON_INLINE PyObject *__Pyx_GetItemInt_List_Fast(PyObject *o, Py_ssize_t i,
                                   ^
    karta/raster/crfuncs.c:6818:32: warning: unused function '__Pyx_GetItemInt_Fast' [-Wunused-function]
    static CYTHON_INLINE PyObject *__Pyx_GetItemInt_Fast(PyObject *o, Py_ssize_t i, int is_list,
                                   ^
    karta/raster/crfuncs.c:6893:27: warning: unused function '__Pyx_ErrRestore' [-Wunused-function]
    static CYTHON_INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb) {
                              ^
    karta/raster/crfuncs.c:6910:27: warning: unused function '__Pyx_ErrFetch' [-Wunused-function]
    static CYTHON_INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb) {
                              ^
    karta/raster/crfuncs.c:7707:32: warning: unused function '__Pyx_PyInt_From_long' [-Wunused-function]
    static CYTHON_INLINE PyObject* __Pyx_PyInt_From_long(long value) {
                                   ^
    karta/raster/crfuncs.c:7744:48: warning: unused function '__pyx_t_float_complex_from_parts' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_float_complex __pyx_t_float_complex_from_parts(float x, float y) {
                                                   ^
    karta/raster/crfuncs.c:7754:30: warning: unused function '__Pyx_c_eqf' [-Wunused-function]
        static CYTHON_INLINE int __Pyx_c_eqf(__pyx_t_float_complex a, __pyx_t_float_complex b) {
                                 ^
    karta/raster/crfuncs.c:7757:48: warning: unused function '__Pyx_c_sumf' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_float_complex __Pyx_c_sumf(__pyx_t_float_complex a, __pyx_t_float_complex b) {
                                                   ^
    karta/raster/crfuncs.c:7763:48: warning: unused function '__Pyx_c_difff' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_float_complex __Pyx_c_difff(__pyx_t_float_complex a, __pyx_t_float_complex b) {
                                                   ^
    karta/raster/crfuncs.c:7775:48: warning: unused function '__Pyx_c_quotf' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_float_complex __Pyx_c_quotf(__pyx_t_float_complex a, __pyx_t_float_complex b) {
                                                   ^
    karta/raster/crfuncs.c:7782:48: warning: unused function '__Pyx_c_negf' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_float_complex __Pyx_c_negf(__pyx_t_float_complex a) {
                                                   ^
    karta/raster/crfuncs.c:7788:30: warning: unused function '__Pyx_c_is_zerof' [-Wunused-function]
        static CYTHON_INLINE int __Pyx_c_is_zerof(__pyx_t_float_complex a) {
                                 ^
    karta/raster/crfuncs.c:7791:48: warning: unused function '__Pyx_c_conjf' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_float_complex __Pyx_c_conjf(__pyx_t_float_complex a) {
                                                   ^
    karta/raster/crfuncs.c:7805:52: warning: unused function '__Pyx_c_powf' [-Wunused-function]
            static CYTHON_INLINE __pyx_t_float_complex __Pyx_c_powf(__pyx_t_float_complex a, __pyx_t_float_complex b) {
                                                       ^
    karta/raster/crfuncs.c:7864:49: warning: unused function '__pyx_t_double_complex_from_parts' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_double_complex __pyx_t_double_complex_from_parts(double x, double y) {
                                                    ^
    karta/raster/crfuncs.c:7874:30: warning: unused function '__Pyx_c_eq' [-Wunused-function]
        static CYTHON_INLINE int __Pyx_c_eq(__pyx_t_double_complex a, __pyx_t_double_complex b) {
                                 ^
    karta/raster/crfuncs.c:7877:49: warning: unused function '__Pyx_c_sum' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_double_complex __Pyx_c_sum(__pyx_t_double_complex a, __pyx_t_double_complex b) {
                                                    ^
    karta/raster/crfuncs.c:7883:49: warning: unused function '__Pyx_c_diff' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_double_complex __Pyx_c_diff(__pyx_t_double_complex a, __pyx_t_double_complex b) {
                                                    ^
    karta/raster/crfuncs.c:7895:49: warning: unused function '__Pyx_c_quot' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_double_complex __Pyx_c_quot(__pyx_t_double_complex a, __pyx_t_double_complex b) {
                                                    ^
    karta/raster/crfuncs.c:7902:49: warning: unused function '__Pyx_c_neg' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_double_complex __Pyx_c_neg(__pyx_t_double_complex a) {
                                                    ^
    karta/raster/crfuncs.c:7908:30: warning: unused function '__Pyx_c_is_zero' [-Wunused-function]
        static CYTHON_INLINE int __Pyx_c_is_zero(__pyx_t_double_complex a) {
                                 ^
    karta/raster/crfuncs.c:7911:49: warning: unused function '__Pyx_c_conj' [-Wunused-function]
        static CYTHON_INLINE __pyx_t_double_complex __Pyx_c_conj(__pyx_t_double_complex a) {
                                                    ^
    karta/raster/crfuncs.c:7925:53: warning: unused function '__Pyx_c_pow' [-Wunused-function]
            static CYTHON_INLINE __pyx_t_double_complex __Pyx_c_pow(__pyx_t_double_complex a, __pyx_t_double_complex b) {
                                                        ^
    karta/raster/crfuncs.c:8025:27: warning: function '__Pyx_PyInt_As_long' is not needed and will not be emitted [-Wunneeded-internal-declaration]
    static CYTHON_INLINE long __Pyx_PyInt_As_long(PyObject *x) {
                              ^
    karta/raster/crfuncs.c:4985:32: warning: unused function '__pyx_f_5numpy_PyArray_MultiIterNew1' [-Wunused-function]
    static CYTHON_INLINE PyObject *__pyx_f_5numpy_PyArray_MultiIterNew1(PyObject *__pyx_v_a) {
                                   ^
    karta/raster/crfuncs.c:5035:32: warning: unused function '__pyx_f_5numpy_PyArray_MultiIterNew2' [-Wunused-function]
    static CYTHON_INLINE PyObject *__pyx_f_5numpy_PyArray_MultiIterNew2(PyObject *__pyx_v_a, PyObject *__pyx_v_b) {
                                   ^
    karta/raster/crfuncs.c:5085:32: warning: unused function '__pyx_f_5numpy_PyArray_MultiIterNew3' [-Wunused-function]
    static CYTHON_INLINE PyObject *__pyx_f_5numpy_PyArray_MultiIterNew3(PyObject *__pyx_v_a, PyObject *__pyx_v_b, PyObject *__pyx_v_c) {
                                   ^
    karta/raster/crfuncs.c:5135:32: warning: unused function '__pyx_f_5numpy_PyArray_MultiIterNew4' [-Wunused-function]
    static CYTHON_INLINE PyObject *__pyx_f_5numpy_PyArray_MultiIterNew4(PyObject *__pyx_v_a, PyObject *__pyx_v_b, PyObject *__pyx_v_c, PyObject *__pyx_v_d) {
                                   ^
    karta/raster/crfuncs.c:5185:32: warning: unused function '__pyx_f_5numpy_PyArray_MultiIterNew5' [-Wunused-function]
    static CYTHON_INLINE PyObject *__pyx_f_5numpy_PyArray_MultiIterNew5(PyObject *__pyx_v_a, PyObject *__pyx_v_b, PyObject *__pyx_v_c, PyObject *__pyx_v_d, PyObject *__pyx_v_e) {
                                   ^
    karta/raster/crfuncs.c:5993:27: warning: unused function '__pyx_f_5numpy_set_array_base' [-Wunused-function]
    static CYTHON_INLINE void __pyx_f_5numpy_set_array_base(PyArrayObject *__pyx_v_arr, PyObject *__pyx_v_base) {
                              ^
    karta/raster/crfuncs.c:6089:32: warning: unused function '__pyx_f_5numpy_get_array_base' [-Wunused-function]
    static CYTHON_INLINE PyObject *__pyx_f_5numpy_get_array_base(PyArrayObject *__pyx_v_arr) {
                                   ^
    38 warnings generated.
    creating build/lib.macosx-10.10-x86_64-3.4
    creating build/lib.macosx-10.10-x86_64-3.4/karta
    creating build/lib.macosx-10.10-x86_64-3.4/karta/raster
    clang -bundle -undefined dynamic_lookup build/temp.macosx-10.10-x86_64-3.4/karta/raster/crfuncs.o -o build/lib.macosx-10.10-x86_64-3.4/karta/raster/crfuncs.so
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/benasher/Code/Python/venvs/karta_test/src/karta/setup.py", line 108, in <module>
        cmdclass = {"build_ext": build_ext},
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/setuptools/command/develop.py", line 32, in run
        self.install_for_development()
      File "/Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/setuptools/command/develop.py", line 117, in install_for_development
        self.run_command('build_ext')
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/benasher/Code/Python/venvs/karta_test/src/karta/setup.py", line 51, in run
        _build_ext.run(self)
      File "/Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 49, in run
        _build_ext.run(self)
      File "/Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/Cython/Distutils/build_ext.py", line 164, in run
        _build_ext.build_ext.run(self)
      File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/Cython/Distutils/build_ext.py", line 172, in build_extensions
        self.build_extension(ext)
      File "/Users/benasher/Code/Python/venvs/karta_test/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 175, in build_extension
        if ext._needs_stub:
    AttributeError: 'Extension' object has no attribute '_needs_stub'
    
    ----------------------------------------
Command "/Users/benasher/Code/Python/venvs/karta_test/bin/python3.4 -c "import setuptools, tokenize; __file__='/Users/benasher/Code/Python/venvs/karta_test/src/karta/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/benasher/Code/Python/venvs/karta_test/src/karta
```

This branch does install successfully if I don't install cython first, so this likely now has to do with the "cythonize" step of installing karta. So, I think the numpy part is solved, but there appears to be a new issue related to installing this branch if you have cython in your setup.

**Comment by njwilson23** [comment] 2015-08-19 21:57
Okay, I can reproduce this. I'll check into it.

**Comment by njwilson23** [comment] 2015-08-26 07:25
Just pushed a change that I think fixes this. I'm travelling right now, but let me know if it's still a problem.

**Comment by benasher44** [comment] 2015-08-26 13:21
Oh awesome! I'm actually traveling myself now, and I don't have the computer with me to test this. I'll be back in at the end of next week, and I'll test and let you know then. Thanks again!

**Comment by benasher44** [comment] 2015-09-07 23:39
Okay. It looks like it gets farther, but I'm experiencing a new issue :/.

After running the following commands in a new virtualenv:
```pip install cython```
```pip install --no-cache-dir -e git+https://github.com/njwilson23/karta@numpyless-install#egg=karta-dev```

I get the following output: https://gist.github.com/benasher44/c7f5790ad5065f464884 (had to link a gist because the output was too long to fit into a comment)

**Comment by njwilson23** [comment] 2015-09-08 01:33
Hmm - thanks for sticking with this.

This first failure in the output is hard, because following your commands I don't reproduce it on my Linux laptop. Could you tell me what version of setuptools you're running?
`python -c "import setuptools; print(setuptools.__version__)"`

The second one (at the end of the file) was due to a typo (`self.extension` should be `self.extensions`) that should be fixed on master. I'm playing around with the master branch a lot right now, but could you see if the same thing happens at tag `v0.4.4`? (a42c2a10ff1ff92214592e7b9aca5528605e4498)

**Comment by benasher44** [comment] 2015-09-08 13:04
Running ```python -c "import setuptools; print(setuptools.__version__)"``` ouputs ```18.0.1```.

I tried your other suggestion, and running ```pip install --no-cache-dir git+https://github.com/njwilson23/karta@v0.4.4#egg=karta-dev``` works fine (no build errors :) ). However, running ```pip install -r requirements.txt``` with this requirements file https://gist.github.com/benasher44/ca981f644adf103e43c1, I get the following output:

```
Collecting karta>=0.4.4 (from -r requirements/prod.txt (line 5))
  Downloading karta-0.4.4.tar.gz (260kB)
    100% |████████████████████████████████| 262kB 1.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/3w/68cpb10s359538q_8rj2fpsh0000gn/T/pip-build-pw0we8bw/karta/setup.py", line 5, in <module>
        import numpy
    ImportError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3w/68cpb10s359538q_8rj2fpsh0000gn/T/pip-build-pw0we8bw/karta
```

**Comment by njwilson23** [comment] 2015-09-08 13:14
Yup. When you do it the second way, it downloads from PyPI, where it gets an older version with the setup file from before you let me know about this bug. Probably I should have tagged the fixed version on Github as 0.4.5.

I might push a new version to PyPI, but I'm hoping to tag 0.5 in the next couple of weeks with some geodetic accuracy and efficiency improvements, so once that's done it should work correctly when installing from both Github and PyPI.

**Comment by benasher44** [comment] 2015-09-08 13:15
Ah okay awesome. Thanks!

**Comment by njwilson23** [comment] 2015-09-20 13:45
I went ahead and pushed 0.4.6 to PyPI, so closing this.

**Closed by njwilson23** 2015-09-20 13:45 UTC

**Comment by benasher44** [comment] 2015-09-20 15:53
Just installed 0.4.6, and everything looks good. Thanks so much!
